### ISSUE TITLE
'bfd.h' file not found

### ISSUE THREAD

**Issue by MikeIsCodeing** [jcdutton/libbeauty#15]
When I compile on my Ubuntu 14.04.1 I get this error:

In file included from bfl.c:34:
./bfl-internal.h:4:10: fatal error: 'bfd.h' file not found

What package do I need to install additionally, I found nothing in the web.

Thanks Mike....

**Comment by jcdutton** [comment]
apt-file is your friend
apt-file find bfd.h
binutils-dev: /usr/include/bfd.h
So, install binutils-dev

**Comment by erriapo** [comment]
Thanks for the tip.
